### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by pattanaponcws** [Final-Project-kmitl/frontend#2]

**Comment by pattanaponcws** [comment]
- [ ] Redesign
- [ ] Design remaining features
- [ ] **Milestone**

**Comment by Sunnyboonyawee** [comment]
![image](https://github.com/user-attachments/assets/8151ab70-a4de-493f-a75f-90968d532c25)

**Comment by Sunnyboonyawee** [comment]
![image](https://github.com/user-attachments/assets/6c82c91c-7dab-4c4a-8656-7dbba0610a3b)
